[package]
name = "crabbiness"
version = "0.1.0"
authors = ["Chris J Arges <christopherarges@gmail.com>"]
edition = "2018"

[dependencies]
rstest = "0.12.0"
bitflags = "1.3"
hexdump = "0.1.0"
macroquad = "0.3"
log = "0.*"
env_logger = "0.9.0"
bumpalo = "3.11.1"
